version: '3.8'

services:
  mongo_db:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"

  mongo_express:
    image: mongo-express:latest
    container_name: mongo_express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo_db
      ME_CONFIG_BASICAUTH_USERNAME: "mongo"
      ME_CONFIG_BASICAUTH_PASSWORD: "mongo"
    ports:
      - "8081:8081"
