name: Deploy Backend to Uberspace

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Server
        run: |
          sshpass -p "${{ secrets.UBERSPACE_PASSWORD }}" 
          ssh -o StrictHostKeyChecking=no ${{ secrets.UBERSPACE_USER }}
          @${{ secrets.UBERSPACE_HOST }} << 'EOF'
            set -e  # Stoppt bei einem Fehler

            # Repo klonen oder updaten
            if [ ! -d "backend-volley/.git" ]; then
              echo "Repo nicht gefunden, klone es..."
              rm -rf backend-volley
              git clone https://github.com/tanhab20/backend-volley.git
            fi

            # Wechsle ins Repository
            cd backend-volley || exit 1
            git pull origin main

            # Installiere Abhängigkeiten
            npm install

            # PM2 neu starten (falls läuft) oder starten
            pm2 delete backend-volley || true  
            pm2 start app.js --name backend-volley

            echo "Backend Deployment erfolgreich!"
          EOF

  tests:
    needs: deploy
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
