name: Deploy to Uberspace

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 #holt sich den aktuellen Code des Repos

      - name: Install sshpass
        run: sudo apt-get install -y sshpass #sshpass installieren, damit das Passwort automatisch 체bergeben wird

      - name: Deploy to Server
        run: |
          sshpass -p "${{ secrets.UBERSPACE_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.UBERSPACE_USER }}@${{ secrets.UBERSPACE_HOST }} << 'EOF' #ssh Verbindung herstellen
            set -e  # Stoppt bei einem Fehler
          
            # Repo klonen oder updaten
            if [ ! -d "backend-volley/.git" ]; then
              echo "Repo nicht gefunden, klone es..."
              rm -rf backend-volley
              git clone https://github.com/tanhab20/backend-volley.git
            fi
          
            # Wechsle ins Repository
            cd backend-volley || exit 1
            git pull origin main

            # Installiere Abh채ngigkeiten & baue das Projekt
            npm install
          
            # PM2 neu starten (falls l채uft) oder starten
            # pm2 ist ein Prozessmanagement-Tool, um Node.js-Anwendungen zu starten
            pm2 delete backend-volley || true  # Fehler ignorieren, falls Prozess nicht existiert
            pm2 start app.js --name backend-volley
          
            echo "Deployment erfolgreich!"
          EOF

  tests:
    needs: deploy  # Dieser Job startet nur, wenn der "deploy"-Job erfolgreich war
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install npm dependencies, cache them korrekt und f체hre alle Cypress-Tests aus
      - name: Cypress run
        uses: cypress-io/github-action@v6
