name: Deploy to Uberspace

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Server
        run: |
          sshpass -p "${{ secrets.UBERSPACE_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.UBERSPACE_USER }}@${{ secrets.UBERSPACE_HOST }} << 'EOF'
            set -e  # Stoppt bei einem Fehler
          
          
            # 2️⃣ Repo klonen oder updaten
            if [ ! -d "volley-backend/.git" ]; then
              echo "⚠️ Repo nicht gefunden, klone es..."
              rm -rf volley-backend
              git clone https://github.com/tanhab20/backend-volley.git
            fi
          
          # 3️⃣ Wechsle ins Repository
            cd backend-volley || exit 1
            git pull origin main

            # 4️⃣ Installiere Abhängigkeiten & baue das Projekt
            npm install
          
            # 5️⃣ PM2 neu starten (falls läuft) oder starten
            pm2 delete volley-backend || true  # Fehler ignorieren, falls Prozess nicht existiert
            pm2 start app.js --name volley-backend
          
            
          
          
          
          
            echo "✅ Deployment erfolgreich!"
          EOF
