name: Deploy to Uberspace

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 #holt sich den aktuellen code des repos

      - name: Install sshpass
        run: sudo apt-get install -y sshpass #sshpass installieren damit das password automatisch übergeben wird

      - name: Deploy to Server
        run: |
          sshpass -p "${{ secrets.UBERSPACE_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.UBERSPACE_USER }}@${{ secrets.UBERSPACE_HOST }} << 'EOF' #ssh verbindung herstellen
            set -e  # Stoppt bei einem Fehler
          
          
            #  Repo klonen oder updaten
            if [ ! -d "backend-volley.git" ]; then
              echo "Repo nicht gefunden, klone es..."
              rm -rf backend-volley
              git clone https://github.com/tanhab20/backend-volley.git
            fi
          
          #  Wechsle ins Repository
            cd backend-volley
            git pull origin main

            #  Installiere Abhängigkeiten & baue das Projekt
            npm install
          
            #  PM2 neu starten (falls läuft) oder starten
            pm2 delete volley-backend || true  # Fehler ignorieren, falls Prozess nicht existiert
            pm2 start app.js --name volley-backend
          
            
          
            echo " Deployment erfolgreich!"
          EOF
